trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - infrastructure/*

pool: Default

stages:
- stage: 'DevPlan'
  displayName: 'Dev Plan'
  jobs:
  - job: 
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'dev.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\dev\variables.tfvars'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'QAPlan'
  displayName: 'QA Plan'
  jobs:
  - job: 
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'qa.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\qa\variables.tfvars'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'StagePlan'
  displayName: 'Stage Plan'
  jobs:
  - job: 
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'stage.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\stage\variables.tfvars'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'ProdPlan'
  displayName: 'Prod Plan'
  jobs:
  - job: 
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'prod.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\prod\variables.tfvars'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'DevApply'
  displayName: 'Dev Apply'
  condition: and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/main'))
  jobs:
  - deployment:
    environment: dev
  - job:
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'dev.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\dev\variables.tfvars -auto-approve'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'DevDestroy'
  displayName: 'Dev Destroy'
  condition: and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/main'))
  dependsOn: DevApply
  jobs:
  - deployment:
    environment: dev
  - job:
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'dev.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\dev\variables.tfvars -auto-approve'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'QAApply'
  displayName: 'QA Apply'
  condition: and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/main'))
  jobs:
  - deployment:
    environment: qa
  - job:
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'qa.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\qa\variables.tfvars -auto-approve'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'QADestroy'
  displayName: 'QA Destroy'
  condition: and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/main'))
  dependsOn: QAApply
  jobs:
  - deployment:
    environment: qa
  - job:
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'qa.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\qa\variables.tfvars -auto-approve'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'StageApply'
  displayName: 'Stage Apply'
  condition: and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/main'))
  jobs:
  - deployment:
    environment: stage
  - job:
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'stage.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\stage\variables.tfvars -auto-approve'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'StageDestroy'
  displayName: 'Stage Destroy'
  condition: and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/main'))
  dependsOn: StageApply
  jobs:
  - deployment:
    environment: stage
  - job:
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'stage.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\stage\variables.tfvars -auto-approve'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'ProdApply'
  displayName: 'Prod Apply'
  condition: and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/main'))
  jobs:
  - deployment:
    environment: prod
  - job:
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'prod.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\prod\variables.tfvars -auto-approve'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'ProdDestroy'
  displayName: 'Prod Destroy'
  condition: and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/main'))
  dependsOn: ProdApply
  jobs:
  - deployment:
    environment: prod
  - job:
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'prod.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\prod\variables.tfvars -auto-approve'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

