trigger:
  branches:
    include:
    - '*'
  paths:
    include:
    - infrastructure/*

pool: Default

stages:
- stage: 'DevPlan'
  displayName: 'Dev Plan'
  jobs:
  - job: 
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'dev.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'plan'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\dev\variables.tfvars'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

    
- stage: 'DevApply'
  displayName: 'Dev Apply'
  condition: and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/main'))
  jobs:
  - deployment:
    environment: dev
  - job:
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'

    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'dev.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'apply'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\dev\variables.tfvars -auto-approve'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

- stage: 'DevDestroy'
  displayName: 'Dev Destroy'
  condition: and(succeeded(),eq(variables['Build.SourceBranch'],'refs/heads/main'))
  dependsOn: DevApply
  jobs:
  - deployment:
    environment: dev
  - job:
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'init'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        backendServiceArm: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'
        backendAzureRmResourceGroupName: 'suvham-tfstate-rg'
        backendAzureRmStorageAccountName: 'suvhamtfstatesa'
        backendAzureRmContainerName: 'suvham-tfstate-container'
        backendAzureRmKey: 'dev.tfstate'
    - task: TerraformTask@5
      inputs:
        provider: 'azurerm'
        command: 'destroy'
        workingDirectory: '$(System.DefaultWorkingDirectory)\infrastructure\'
        commandOptions: '-var-file=environments\dev\variables.tfvars -auto-approve'
        environmentServiceNameAzureRM: 'suvham_paul@epam.com(a53670da-bf9b-4c7d-825a-7544c720e890)'

