# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    include:
    - infrastructure/*


pool:
  vmImage: ubuntu-latest

stages:
- stage: Tf Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: 
    steps:
    - task: TerraformInstaller@1
      inputs:
        terraformVersion: 'latest'
        
      
