trigger:
  branches:
    include:
    - 'main'
  paths:
    include:
    - application


pool: Default

stages:
- stage: 'Archive'
  displayName: 'Archive App'
  jobs:
  - job:
    steps:
    - task: NodeTool@0
      inputs:
        versionSource: 'spec'
        versionSpec: '16.x'
      displayName: 'Install Nodejs'
    
    - script: cd application && npm install
      displayName: 'Npm install'
    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/application/'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(System.DefaultWorkingDirectory)/zipped/$(Build.BuildId).zip'
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(System.DefaultWorkingDirectory)/zipped/$(Build.BuildId).zip'
        ArtifactName: '$(Build.BuildId).zip'
        publishLocation: 'Container'

- stage: 'DevDeploy'
  displayName: 'Dev Deploy'
  jobs:
  - job:
    steps:
    
    - task: DownloadBuildArtifacts@1
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: '$(Build.BuildId).zip'
        downloadPath: '$(System.DefaultWorkingDirectory)/zipped/'
    
    