apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-app
  namespace: default
  labels:
    app: k8s-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: k8s-app
  template:
    metadata:
      labels:
        app: k8s-app
    spec:
      containers:
        - name: k8s-app 
          image: myacr.azurecr.io/image_name:latest
          ports:
            - containerPort: 8080
          env:
            - name: SQL_USER 
              valueFrom:
                secretKeyRef:
                  name: dbcred
                  key: sql-user
            - name: SQL_PASSWORD 
              valueFrom:
                secretKeyRef:
                  name: dbcred
                  key: sql-password 
            - name: SQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: dbcred
                  key: sql-database
            - name: SQL_SERVER
              valueFrom:
                secretKeyRef:
                  name: dbcred
                  key: sql-server
            - name: SQL_ENCRYPT
              value: "true"